[crates]
cc = {name = "cc", version = '1.0.67'}
home = {name = "home", git_url = "https://github.com/brson/home", git_hash = "32044e53dfbdcd32bafad3109d1fbab805fc0f40"}
rustc_tools_util = {name = "rustc_tools_util", version = '0.2.0'}
