use std::io::Write;
fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let patterns_dir = std::path::Path::new(&crate_dir).join("../../docs/patterns-pest");
    if !patterns_dir.exists() {
        eprintln!(
            "cargo:warning=Patterns directory {:?} does not exist, skip scanning",
            patterns_dir
        );
        return;
    }
    println!("cargo:rerun-if-changed={}", patterns_dir.display());

    let collect_patterns = |dir: &std::path::Path, category: &str, out: &mut std::fs::File| {
        let mut collections = Vec::new();
        for entry in std::fs::read_dir(dir).unwrap() {
            let entry = entry.unwrap();
            let path = entry.path();
            if path.extension().and_then(|ext| ext.to_str()) == Some("rpl") {
                let name = path.file_name().unwrap().to_str().unwrap();
                collections.push(name.to_string());
            }
        }
        collections.sort_by_key(|name| name.clone());
        for name in collections {
            writeln!(out, "        \"{category}/{name}\",").unwrap();
        }
    };

    let out_file = std::path::Path::new(&crate_dir).join("src/patterns.rs");
    let mut out = std::fs::File::create(out_file).unwrap();

    out.write_all(
        br#"//! This file is generated by build.rs

/// This macro will return a tuple of the path and the content of the file.
///
/// Please pass a path related to `docs/patterns-pest`.
macro_rules! default_pattern {
    ($path:literal) => {
        (
            concat!("docs/patterns-pest/", $path),
            include_str!(concat!("../../../docs/patterns-pest/", $path)),
        )
    };
}

macro_rules! default_patterns {
    ($($name:literal),* $(,)?) => {
        vec![$(
            default_pattern!($name),
        )*]
    };
}
"#,
    )
    .unwrap();
    writeln!(
        out,
        "
pub fn patterns() -> Vec<(&'static str, &'static str)> {{
    default_patterns![
        // When you add a pattern to the list below,
        // ensure that its order matches the file system's order.
        // (To ensure consistency of output information during testing)"
    )
    .unwrap();
    writeln!(out, r"        // Clippy lints").unwrap();
    collect_patterns(&patterns_dir.join("clippy"), "clippy", &mut out);
    writeln!(out, r"        // CVE patterns").unwrap();
    collect_patterns(&patterns_dir.join("cve"), "cve", &mut out);
    writeln!(out, r"        // Common patterns based on Rust's UB").unwrap();
    collect_patterns(&patterns_dir.join("ub"), "ub", &mut out);
    writeln!(out, "    ]").unwrap();
    writeln!(out, "}}").unwrap();
}
